### ISSUE TITLE
Raw text of the dataset

### ISSUE THREAD

**Issue by WanzhengZhu** [rishabhmisra/News-Headlines-Dataset-For-Sarcasm-Detection#2]
Thank you for the dataset. 
Each data point contains three components: 1) is_sarcastic, 2) headline and 3) article_link. 
Can you provide raw text of the article as well? The article-link is harder to process. 
Thank you!

**Comment by rishabhmisra** [comment]
`article_link` is provided so that interested folks can scrape further data as per their needs. If you are looking for a resource on how to scrape data, I've written a blog post here: https://towardsdatascience.com/a-practical-guide-to-collecting-ml-datasets-476f1ecf5e35. Hope this helps!
